### ISSUE TITLE
希望增加时间类型的支持

### ISSUE THREAD

**Issue by 1409130272** [rule-engine/rule-engine#6]
大佬好，boot rule做的非常不错，在开源规则引擎且带有可视化规则配置页面的项目中，boot rule应该是名列前茅，据我所知，可视化配置的开源规则引擎只有 urule和boot rule，urule开源版本已经无人维护了，反馈问题均说请使用商业版本，目前只剩下boot rule一个了，经过一下午的体验，整体还是非常不错的，只是时间这块可能没有支持，只能使用时间戳方式间接实现，故麻烦大佬支持时间类型，可以做到 输入一个标准的时间字符串，比如“2021-02-01 00:00:00” 来进行规则校验，或者使用时间控件，点选时间自动映射成时间格式。
       最后，希望boot rule成为国产开源可视化规则引擎中的领头羊，向世界展示中国实力，加油！！！

**Comment by dingqianwen** [comment]
感谢你的建议，今晚我会改造下规则引擎能支持时间类型，可视化配置方面待有充分时进行改造。

**Comment by dingqianwen** [comment]
> ```
>    大佬好，boot rule做的非常不错，在开源规则引擎且带有可视化规则配置页面的项目中，boot rule应该是名列前茅，据我所知，可视化配置的开源规则引擎只有 urule和boot rule，urule开源版本已经无人维护了，反馈问题均说请使用商业版本，目前只剩下boot rule一个了，经过一下午的体验，整体还是非常不错的，只是时间这块可能没有支持，只能使用时间戳方式间接实现，故麻烦大佬支持时间类型，可以做到 输入一个标准的时间字符串，比如“2021-02-01 00:00:00” 来进行规则校验，或者使用时间控件，点选时间自动映射成时间格式。
>    最后，希望boot rule成为国产开源可视化规则引擎中的领头羊，向世界展示中国实力，加油！！！
> ```

后端已经提交，请查看：https://github.com/rule-engine/rule-engine/commit/007605f90f4faf5e674da0cb22a5f2e0e255c23a

**Comment by dingqianwen** [comment]
> ```
>    大佬好，boot rule做的非常不错，在开源规则引擎且带有可视化规则配置页面的项目中，boot rule应该是名列前茅，据我所知，可视化配置的开源规则引擎只有 urule和boot rule，urule开源版本已经无人维护了，反馈问题均说请使用商业版本，目前只剩下boot rule一个了，经过一下午的体验，整体还是非常不错的，只是时间这块可能没有支持，只能使用时间戳方式间接实现，故麻烦大佬支持时间类型，可以做到 输入一个标准的时间字符串，比如“2021-02-01 00:00:00” 来进行规则校验，或者使用时间控件，点选时间自动映射成时间格式。
>    最后，希望boot rule成为国产开源可视化规则引擎中的领头羊，向世界展示中国实力，加油！！！
> ```

前端日期配置已经编写完毕，待测试没有问题即可体验此功能！

**Comment by dingqianwen** [comment]
> ```
>    大佬好，boot rule做的非常不错，在开源规则引擎且带有可视化规则配置页面的项目中，boot rule应该是名列前茅，据我所知，可视化配置的开源规则引擎只有 urule和boot rule，urule开源版本已经无人维护了，反馈问题均说请使用商业版本，目前只剩下boot rule一个了，经过一下午的体验，整体还是非常不错的，只是时间这块可能没有支持，只能使用时间戳方式间接实现，故麻烦大佬支持时间类型，可以做到 输入一个标准的时间字符串，比如“2021-02-01 00:00:00” 来进行规则校验，或者使用时间控件，点选时间自动映射成时间格式。
>    最后，希望boot rule成为国产开源可视化规则引擎中的领头羊，向世界展示中国实力，加油！！！
> ```

已经编写完毕并上传以及发布，欢迎测试！

**Comment by dingqianwen** [comment]
done
